# Google Cloud Workstations Custom Image
# Base: code-oss
# Generated by workstation-image.sh

FROM us-central1-docker.pkg.dev/cloud-workstations-images/predefined/code-oss:latest

# Switch to root for installing packages
USER root

# =============================================================================
# Terraform
# =============================================================================
ARG TERRAFORM_VERSION=1.7.0
RUN curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    mv terraform /usr/local/bin/ && \
    rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Copy startup script for VS Code extensions (as root for proper ownership)
# Named 120 to run AFTER 110_start-code-oss.sh (- sorts before _)
COPY --chmod=755 scripts/120-install-extensions.sh /etc/workstation-startup.d/120-install-extensions.sh

# Switch back to default user
USER 1000
